In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('loan_approval_dataset.csv')

In [3]:
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [4]:
df.shape

(4269, 13)

In [6]:
df.describe()

,loan_id,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
count,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4269.000000,4269.000000,4.269000e+03,4.269000e+03,4.269000e+03,4.269000e+03
mean,2135.000000,2.498712,5.059124e+06,1.513345e+07,10.900445,599.936051,7.472617e+06,4.973155e+06,1.512631e+07,4.976692e+06
std,1232.498479,1.695910,2.806840e+06,9.043363e+06,5.709187,172.430401,6.503637e+06,4.388966e+06,9.103754e+06,3.250185e+06
min,1.000000,0.000000,2.000000e+05,3.000000e+05,2.000000,300.000000,-1.000000e+05,0.000000e+00,3.000000e+05,0.000000e+00
25%,1068.000000,1.000000,2.700000e+06,7.700000e+06,6.000000,453.000000,2.200000e+06,1.300000e+06,7.500000e+06,2.300000e+06
50%,2135.000000,3.000000,5.100000e+06,1.450000e+07,10.000000,600.000000,5.600000e+06,3.700000e+06,1.460000e+07,4.600000e+06
75%,3202.000000,4.000000,7.500000e+06,2.150000e+07,16.000000,748.000000,1.130000e+07,7.600000e+06,2.170000e+07,7.100000e+06
max,4269.000000,5.000000,9.900000e+06,3.950000e+07,20.000000,900.000000,2.910000e+07,1.940000e+07,3.920000e+07,1.470000e+07

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   loan_id                    4269 non-null   int64
 1    no_of_dependents          4269 non-null   int64
 2    education                 4269 non-null   object
 3    self_employed             4269 non-null   object
 4    income_annum              4269 non-null   int64
 5    loan_amount               4269 non-null   int64
 6    loan_term                 4269 non-null   int64
 7    cibil_score               4269 non-null   int64
 8    residential_assets_value  4269 non-null   int64
 9    commercial_assets_value   4269 non-null   int64
 10   luxury_assets_value       4269 non-null   int64
 11   bank_asset_value          4269 non-null   int64
 12   loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

In [10]:
df.columns = df.columns.str.strip()

In [11]:
from scipy import stats

numerical_features = ['no_of_dependents', 'income_annum', 'loan_amount', 'loan_term', 
                       'cibil_score', 'residential_assets_value', 'commercial_assets_value', 
                       'luxury_assets_value', 'bank_asset_value']


z_scores = stats.zscore(df[numerical_features])

In [12]:
z_scores

,no_of_dependents,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,-0.294102,1.617979,1.633052,0.192617,1.032792,-0.780058,2.877289,0.832028,0.930304
1,-1.473548,-0.341750,-0.324414,-0.508091,-1.061051,-0.733924,-0.631921,-0.694993,-0.515936
2,0.295621,1.439822,1.610933,1.594031,-0.544840,-0.057300,-0.107818,1.996520,2.407316
3,0.295621,1.119139,1.721525,-0.508091,-0.771045,1.649637,-0.381263,0.897943,0.899533
4,1.475067,1.689242,1.002681,1.594031,-1.264055,0.757724,0.735304,1.568075,0.007172
...,...,...,...,...,...,...,...,...,...
4264,1.475067,-1.446324,-1.419268,0.192617,-1.641063,-0.718546,-1.019301,-1.299210,-1.285213
4265,-1.473548,-0.626801,-0.423946,1.594031,-0.237434,-0.503257,-0.472412,-0.453306,-0.946732
4266,-0.294102,0.513405,0.969504,1.243677,-0.829046,-0.964591,1.692361,0.326683,0.714907
4267,-0.883825,-0.341750,-0.258059,-0.508091,1.044393,0.111856,-0.973727,-0.112748,0.253341
4268,-0.883825,1.475453,1.610933,-0.157737,0.040972,1.588126,1.555638,2.260178,2.161148

In [14]:
threshold = 3
# calculate the ouliers in the dataframe
outliers = np.any(np.abs(z_scores) > threshold, axis=1)

# Filter out the outliers
df_clean = df[~outliers]

# Verify the number of rows before and after outlier removal
print("Original number of rows:", len(df))
print("Number of rows after outlier removal:", len(df_clean))

Original number of rows: 4269
Number of rows after outlier removal: 4236

In [18]:
df = df_clean.drop('loan_id', axis = 1)

In [52]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [26]:
encoder = LabelEncoder()
scaler = StandardScaler()

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   loan_id                   4269 non-null   int64
 1   no_of_dependents          4269 non-null   int64
 2   education                 4269 non-null   object
 3   self_employed             4269 non-null   object
 4   income_annum              4269 non-null   int64
 5   loan_amount               4269 non-null   int64
 6   loan_term                 4269 non-null   int64
 7   cibil_score               4269 non-null   int64
 8   residential_assets_value  4269 non-null   int64
 9   commercial_assets_value   4269 non-null   int64
 10  luxury_assets_value       4269 non-null   int64
 11  bank_asset_value          4269 non-null   int64
 12  loan_status               4269 non-null   object
dtypes: int64(10), object(3)
memory usage: 433.7+ KB

In [78]:
X_train

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
2135,2136,0,Graduate,Yes,6400000,16900000,16,759,16200000,7100000,15200000,3100000
2578,2579,3,Graduate,Yes,3000000,7100000,6,415,2000000,5700000,9500000,2500000
2190,2191,2,Graduate,Yes,5600000,21000000,18,883,9800000,1600000,20900000,6000000
3654,3655,1,Not Graduate,Yes,300000,900000,20,419,800000,0,600000,300000
291,292,1,Graduate,Yes,5800000,19500000,20,431,13800000,5000000,15600000,3300000
...,...,...,...,...,...,...,...,...,...,...,...,...
3971,3972,4,Graduate,Yes,8000000,31200000,6,482,19800000,11500000,22200000,5700000
571,572,0,Graduate,No,4700000,17500000,2,701,5400000,2300000,11700000,7000000
1197,1198,5,Graduate,Yes,7500000,28200000,2,440,8200000,5800000,24400000,6000000
2801,2802,3,Graduate,Yes,4400000,10000000,8,875,5900000,5200000,11700000,4100000
3491,3492,2,Not Graduate,No,8100000,17500000,4,674,10800000,12700000,23200000,9300000

In [31]:
categorical_features = ['education', 'self_employed']

In [132]:
cf = ColumnTransformer(transformers = [
    ('Encoding', OneHotEncoder(handle_unknown='ignore'), categorical_features),
    ('Scaling', StandardScaler(), numerical_features)
], remainder = 'passthrough')

In [133]:
X = df.drop(columns = ['loan_id', 'loan_status'], axis=1)
y = df['loan_status']

In [134]:
from sklearn.tree import DecisionTreeClassifier

In [135]:
from sklearn.pipeline import Pipeline

In [136]:
decision_tree = DecisionTreeClassifier(max_depth = 7 )

In [137]:
pipe = Pipeline(steps=[
    ('preprocessor', cf),
    ('classifier', DecisionTreeClassifier(random_state=42, max_depth = 7))
])

In [138]:
from sklearn.model_selection import train_test_split

In [139]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 44)

In [140]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Encoding',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['education',
                                                   'self_employed']),
                                                 ('Scaling', StandardScaler(),
                                                  ['no_of_dependents',
                                                   'income_annum',
                                                   'loan_amount', 'loan_term',
                                                   'cibil_score',
                                                   'residential_assets_value',
                                                   'commercial_assets_value',
                                                   'luxury_assets_value',
                                                   'bank_asset_value'])])),
                ('classifier',
                 DecisionTreeClassifier(max_depth=7, random_state=42))])

In [141]:
y_pred = pipe.predict(X_test)

In [142]:
from sklearn.metrics import accuracy_score

In [143]:
accuracy_score(y_test, y_pred)

0.9672131147540983

In [144]:
import pickle

In [145]:
with open('loan_approval_pipeline.pkl', 'wb') as file:
    pickle.dump(pipe, file)

In [146]:
with open('loan_approval_pipeline.pkl', 'rb') as file:
    model_pipe = pickle.load(file)

In [147]:
X_train.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
2135,0,Graduate,Yes,6400000,16900000,16,759,16200000,7100000,15200000,3100000
2578,3,Graduate,Yes,3000000,7100000,6,415,2000000,5700000,9500000,2500000
2190,2,Graduate,Yes,5600000,21000000,18,883,9800000,1600000,20900000,6000000
3654,1,Not Graduate,Yes,300000,900000,20,419,800000,0,600000,300000
291,1,Graduate,Yes,5800000,19500000,20,431,13800000,5000000,15600000,3300000

In [148]:
prediction = (
    2, 'Graduate', 'No', 9600000, 29900000, 12, 778, 2400000, 17600000, 22700000, 8000000
)

# Create a DataFrame for the prediction data
prediction_df = pd.DataFrame([prediction], columns=[
    'no_of_dependents', 'education', 'self_employed', 'income_annum', 'loan_amount', 'loan_term', 
    'cibil_score', 'residential_assets_value', 'commercial_assets_value', 
    'luxury_assets_value', 'bank_asset_value'
])

In [149]:
model_pipe.predict(prediction_df)

array([' Approved'], dtype=object)